version: '3.8'

services:
  todo-app:
    build: ./
    command: ./wait-for-postgres.sh db ./todo-app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'andry_development'
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

volumes:
  pgdata:
  redisdata:
